module.exports = [
    {
        ignores: ['**/node_modules/**', 'assets/js/runtime/master/lib/**/*.js']
    },
    {
        files: ['assets/js/runtime/master/**/*.js', 'assets/js/editor/**/*.js'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'script',
            globals: {
                AFRAME: 'readonly',
                Blob: 'readonly',
                CustomEvent: 'readonly',
                Element: 'readonly',
                File: 'readonly',
                FormData: 'readonly',
                MediaRecorder: 'readonly',
                NAF: 'readonly',
                Stats: 'readonly',
                THREE: 'readonly',
                URL: 'readonly',
                URLSearchParams: 'readonly',
                alert: 'readonly',
                console: 'readonly',
                dat: 'readonly',
                document: 'readonly',
                easyrtc: 'readonly',
                fetch: 'readonly',
                gtag: 'readonly',
                lil: 'readonly',
                mdc: 'readonly',
                navigator: 'readonly',
                performance: 'readonly',
                requestAnimationFrame: 'readonly',
                cancelAnimationFrame: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
                window: 'readonly',

                // VRodos Editor & Runtime Globals
                VRODOSMaster: 'readonly',
                vrodos_data: 'readonly',
                vrodos_scene_data: 'readonly',
                envir: 'readonly',
                transform_controls: 'readonly',
                avatarControlsEnabled: 'readonly',
                selected_object_name: 'readonly',
                VRodos_LoaderMulti: 'readonly',
                vrodosGetPointerLockObject: 'readonly',
                triggerAutoSave: 'readonly',
                deleteFomScene: 'readonly',
                pauseClickFun: 'readonly',
                addCelOutline: 'readonly',
                removeAllCelOutlines: 'readonly',
                addInHierarchyViewer: 'readonly',
                setTransformControlsSize: 'readonly'
            }
        },
        rules: {
            // Core correctness rules comparable to ESLint's recommended set.
            'constructor-super': 'error',
            'for-direction': 'error',
            'getter-return': 'error',
            'no-async-promise-executor': 'error',
            'no-case-declarations': 'warn',
            'no-class-assign': 'error',
            'no-compare-neg-zero': 'error',
            'no-cond-assign': 'error',
            'no-const-assign': 'error',
            'no-constant-binary-expression': 'error',
            'no-constant-condition': ['error', { checkLoops: false }],
            'no-control-regex': 'error',
            'no-debugger': 'error',
            'no-delete-var': 'error',
            'no-dupe-args': 'error',
            'no-dupe-class-members': 'error',
            'no-dupe-else-if': 'error',
            'no-dupe-keys': 'error',
            'no-duplicate-case': 'error',
            'no-empty': ['error', { allowEmptyCatch: true }],
            'no-empty-character-class': 'error',
            'no-empty-pattern': 'error',
            'no-ex-assign': 'error',
            'no-fallthrough': 'error',
            'no-func-assign': 'error',
            'no-global-assign': 'error',
            'no-import-assign': 'error',
            'no-invalid-regexp': 'error',
            'no-irregular-whitespace': 'error',
            'no-loss-of-precision': 'error',
            'no-misleading-character-class': 'error',
            'no-new-native-nonconstructor': 'error',
            'no-nonoctal-decimal-escape': 'error',
            'no-obj-calls': 'error',
            'no-octal': 'error',
            'no-prototype-builtins': 'error',
            'no-redeclare': 'warn',
            'no-regex-spaces': 'error',
            'no-self-assign': 'error',
            'no-setter-return': 'error',
            'no-shadow-restricted-names': 'error',
            'no-sparse-arrays': 'error',
            'no-this-before-super': 'error',
            'no-undef': 'error',
            'no-unexpected-multiline': 'error',
            'no-unreachable': 'error',
            'no-unsafe-finally': 'error',
            'no-unsafe-negation': 'error',
            'no-unsafe-optional-chaining': 'error',
            'no-unused-labels': 'error',
            'no-useless-backreference': 'error',
            'no-useless-catch': 'error',
            'no-useless-escape': 'warn',
            'no-with': 'error',
            'require-yield': 'error',
            'use-isnan': 'error',
            'valid-typeof': 'error',

            // Runtime scripts intentionally share browser globals across files.
            'no-unused-vars': ['warn', {
                args: 'after-used',
                argsIgnorePattern: '^_',
                varsIgnorePattern: '^_',
                caughtErrors: 'none'
            }],

            // Useful safety defaults for browser/A-Frame runtime code.
            'array-callback-return': 'error',
            'block-scoped-var': 'error',
            'consistent-return': 'warn',
            'curly': ['error', 'multi-line'],
            'default-case': 'warn',
            'dot-notation': 'warn',
            'eqeqeq': ['warn', 'smart'],
            'guard-for-in': 'error',
            'no-alert': 'warn',
            'no-caller': 'error',
            'no-else-return': 'warn',
            'no-empty-function': 'warn',
            'no-eval': 'error',
            'no-extend-native': 'error',
            'no-extra-bind': 'warn',
            'no-floating-decimal': 'error',
            'no-implicit-coercion': 'warn',
            'no-implied-eval': 'error',
            'no-invalid-this': 'off',
            'no-iterator': 'error',
            'no-labels': 'error',
            'no-lone-blocks': 'error',
            'no-loop-func': 'warn',
            'no-multi-assign': 'warn',
            'no-new-func': 'error',
            'no-new-wrappers': 'error',
            'no-octal-escape': 'error',
            'no-param-reassign': 'off',
            'no-proto': 'error',
            'no-return-assign': ['error', 'except-parens'],
            'no-script-url': 'error',
            'no-self-compare': 'error',
            'no-sequences': 'error',
            'no-template-curly-in-string': 'warn',
            'no-throw-literal': 'error',
            'no-unmodified-loop-condition': 'warn',
            'no-unused-expressions': 'error',
            'no-use-before-define': ['warn', { functions: false, classes: true, variables: false }],
            'no-useless-call': 'warn',
            'no-useless-concat': 'warn',
            'no-var': 'error',
            'object-shorthand': ['warn', 'properties'],
            'one-var': ['warn', 'never'],
            'prefer-const': 'error',
            'prefer-template': 'error',
            'arrow-body-style': ['warn', 'as-needed'],
            'prefer-arrow-callback': 'warn',
            'radix': 'error',
            'yoda': 'warn'
        }
    }
];
